### ISSUE TITLE
Not getting initialised. 

### ISSUE THREAD

**Issue by Kiranrajkathula** [taxpon/PolymerForm#1]
thanks for plugin.
I couldn't initialise the form, when the data is pre-filled from the api. But when i focus on input field, everything is working fine.
![prefill](https://cloud.githubusercontent.com/assets/13016029/12080365/585aaa58-b27e-11e5-8d5b-6b1217805d99.PNG)

What is the solution to check the data in input field and move labels up

**Comment by taxpon** [comment]
I added default value option. Please refere [here](http://taxpon.github.io/PolymerForm/#example-default-value)
